apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-stream.conf: |-
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    stream {

      upstream redis_backends {
        server svc2redis1:6379 weight=80;
        server svc2redis2:6379 weight=20;
      }
      server {
        listen 6379;
        proxy_pass redis_backends;
      }
    }
