apiVersion: v1
kind: Service
metadata:
  name: svc2nginx
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30000
      port: 8080
      targetPort: 8080
    - name: redis
      nodePort: 30001
      port: 6379
      targetPort: 6379
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc2redis1
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis1
---
apiVersion: v1
kind: Service
metadata:
  name: svc2redis2
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis2
